//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TareaProgramadaCableColor.Conexion
{
    using System;
    using System.Collections.Generic;
    
    public partial class cableColor
    {
        public int id { get; set; }
        public string codCliente { get; set; }
        public string tipoSaldo { get; set; }
        public string codigoResultado { get; set; }
        public string mensajeResultado { get; set; }
        public string nombreCliente { get; set; }
        public string telefonos { get; set; }
        public string saldo { get; set; }
        public string cajero { get; set; }
        public string fecha { get; set; }
        public string hora { get; set; }
        public string codAgencia { get; set; }
        public string refBanco { get; set; }
        public string identificadorBanco { get; set; }
        public string numReferencia { get; set; }
        public string facts { get; set; }
        public string dets { get; set; }
        public string identificador_unico_consulta { get; set; }
        public string identificador_unico_pago { get; set; }
        public string identificador_unico_reversion { get; set; }
        public string mensajeConsulta { get; set; }
        public string mensajePago { get; set; }
        public string mensajeReversion { get; set; }
        public Nullable<System.DateTime> fechaTransaccion { get; set; }
    }
}
